apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.202.181.234:8001
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMWQzODZiOTZmODMzNTRjOTk0MTcxYzkxNGIwNzkyMzFjZWI0ZDE4ZCIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGYyZjU2MjQyZTUzYThmYzhmNmY3ZTJkMDRlNjAyNWIiLCJleHAiOjE1NjUwNTQzNjEsImlhdCI6MTU2NTAyNTU2MSwic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.LY958d_HeL6mgqeSr6RxWRkaWd_IbQhefJAuaF-GrRkUmLRRQA_kN_733GcsZPD_TaO4VSJ35Z43GR1adwNa7-QrY0TkHV5BDbCqsuE0IGOOB-1YTqq-1EGIgjix_cS9OBo5wcgjW79CMJZVTOEWpNy8VZpT-d2E8MIJwdwscDWtsH1UnIc0wlR-uz01btGSDWzpIKNPux6CRZ_oNPOrIsyq6ZhowrQCXT8-OzQjerW9ny2pFSOzv_hNveJcCBq8nmHqwGN5dGIYQzXa4euiBK1BXkm4hi7xSZh2wgjU0U3OuERUJ5PY9TjNG6We51IGGb9wD0apz4CO-KRbnIOcbA
