apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.202.181.234:8001
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMjY5YjYwNDU5YWNlMDYwOTg4ODAxYTE3NTRjMjA5YTVkZTQ2NmExNSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGYyZjU2MjQyZTUzYThmYzhmNmY3ZTJkMDRlNjAyNWIiLCJleHAiOjE1NjQ3NTQ3MjQsImlhdCI6MTU2NDcyNTkyNCwic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.VNTrpYt1E-ypP5ZFUyoJ1xUwJbEDgkcuQrpIPJv0l-MkpMYKJuvHDwus7932wnywLkIWIm6UjjVF-DVEX1IV9FaNatv5dEjGzQA_58GdRWiOpgFuAjKj_fXQaw2vXe0Sp0t86W942Wg2Dp4SF_csmz4eybhCvjLCmnS7D2eHoz8p-M6YjEv1ps1ep35S5mBtPDYQviUrjHV0ypLJvDNIUOFdnppYozuh8obxy9TTenhWiZfPxYdMHe_dSCFx0rlV4b1G3Q_ZHbfssrt3bfL15VNB5f0YZvPTJgbcwzawEoaD3HRv1a-mm291UMkQTg97WeWVPITSdGB1afHcAf8r6Q
