apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.202.181.234:8001
  name: mycluster.icp
contexts:
- context:
    cluster: mycluster.icp
    namespace: default
    user: admin
  name: mycluster.icp-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMTk4MmY4ZjJmMTJiMjI4OWE5MThhZWI1MGEwMWRiYzA1NzBiZDQ2NyIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGYyZjU2MjQyZTUzYThmYzhmNmY3ZTJkMDRlNjAyNWIiLCJleHAiOjE1NjQ3NDY4NDUsImlhdCI6MTU2NDcxODA0NSwic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.M8IsUBKnyhsNBo2-MtamuCk3R_jl1LqvRmTg0_kxtTNJ3k7Kc3lq7z7nbDccXEnXKUw0ieQPvEybKxfHd2doob4rVzMs09RO8pkysZ_XxsJ7yoNtSm4Ih45cSmTZGVy8fFQ5-QnyQf-FbTt4TLTAiEOYb3nJE8GAi6MbE1N52xYsR5311dHxR_HZHBIYYZC_9XOO9Sxp88ClTLsvp1MLbvTDJrS1-ygs6uklZgKOXKZ45RW7L7SYGRFQ7Lo6nYa_qEBJrNRFJcRlXfLJpPHFbv66RS58daGzthMSkzcQhRxQC3O8zL_8Wom1yHpaed6lvz3eXGmfY0PviCbIxIFp9g
