apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://icp-console.9.204.169.185.nip.io:8443
  name: mycluster
- cluster:
    insecure-skip-tls-verify: true
    server: https://prod2-master.fyre.ibm.com:8443
  name: prod2-master-fyre-ibm-com:8443
contexts:
- context:
    cluster: prod2-master-fyre-ibm-com:8443
    namespace: ace
    user: admin/prod2-master-fyre-ibm-com:8443
  name: ace/prod2-master-fyre-ibm-com:8443/admin
- context:
    cluster: prod2-master-fyre-ibm-com:8443
    namespace: default
    user: admin/prod2-master-fyre-ibm-com:8443
  name: default/prod2-master-fyre-ibm-com:8443/admin
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: ace/prod2-master-fyre-ibm-com:8443/admin
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: BFP4ZnKLdKUJReSXkzhHNK1jp-dFH9Huo7oaKy03B5nQ
- name: admin/prod2-master-fyre-ibm-com:8443
  user:
    token: pMO49Iw54XekPEgEWHxCzSDUHnoxJP0MRPEsTzNK6Y4
