apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://prod-master.fyre.ibm.com:8443
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: ace
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: GGCtRus746lOTie6v2LpcVVXJ1TGv_kjOuZoeKXjsVVt
