apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  selector:
    matchLabels:
      app: $appname
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: $appname
    spec:
      containers:
      - name: $appname
        image: $targetrepo/$appname
        imagePullPolicy: Always
        ports:
        - containerPort: 7600
        - containerPort: 7800
        - containerPort: 7843
---
apiVersion: v1        
kind: Service
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  type: NodePort
  ports:
    - name: webui
      nodePort: 31304
      port: 7600
      targetPort: 7600
    - name: http
      nodePort: 31305
      port: 7800
      targetPort: 7800
    - name: https
      nodePort: 31306
      port: 7843
      targetPort: 7843
  selector:
   app: $appname
