kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: $appname
spec:
  template: 
    metadata:
      labels:
        name: $appname
    spec:
      containers:
        - name: $appname
          image: $targetrepo/$appname
          ports:
            - containerPort: 7600
              protocol: TCP
            - containerPort: 7800
              protocol: TCP
            - containerPort: 7843
              protocol: TCP
  replicas: 1 
  triggers:
    - type: ConfigChange 
    - type: ImageChange 
      imageChangeParams:
        automatic: true
        containerNames:
          - $appname
        from:
          kind: ImageStreamTag
          name: $appname:latest
  strategy: 
    type: Rolling
  paused: false 
  revisionHistoryLimit: 2 
  minReadySeconds: 0 
---
apiVersion: v1        
kind: Service
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  type: NodePort
  ports:
    - name: webui
      nodePort: 30608
      port: 7600
      targetPort: 7600
    - name: http
      nodePort: 30603
      port: 7800
      targetPort: 7800
    - name: https
      nodePort: 30619
      port: 7843
      targetPort: 7843
  selector:
   name: $appname
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: $appname
  name: $appname
  namespace: ace
spec:
  host: pingapp-ace.9.204.169.185.nip.io
  port:
    targetPort: http
  to:
    kind: Service
    name: $appname
    weight: 100
  wildcardPolicy: None
